name: Run Auto Generate JSON with C# File

on:
  push:
    branches:
        - main
        - master
        - Skua
        - dev
        - 'feature/*'
  pull_request:
    types: [closed]

jobs:
  run-csharp-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Run C# file
      run: dotnet run Program.cs --project SkuaScriptsGenerator/SkuaScriptsGenerator.csproj > scripts.json

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: scripts.json
        path: scripts.json

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Automatic commit by GitHub Actions'
        files: 'scripts.json'
        push: true
        push_options: '--force'

    - name: Delete artifact
      uses: geekyeggo/delete-artifact@v2
      with:
        name: scripts.json